### PR TITLE
Update Atom to 0.177.0

### PR DESCRIPTION
**Pull request by t-richards**
https://github.com/atom/atom/releases/tag/v0.177.0

### CODE REVIEW

**Comment by sjug** [comment]
Hey Tom,

Thanks for the pull request, my bad as I was slow to update git with the latest PKGBUILD. I've already pushed it to AUR and I've updated the repo as well. Should I add the .SRCINFO to .gitignore?

Have you had any luck building 0.177 with io.js?

**Comment by t-richards** [comment]
I would personally ignore the .SRCINFO file, since it is generated by `makepkg`. Unfortunately, I haven't had any luck with io.js yet either. I'll make extra commits on this branch if I come up with something :smile:

**Comment by sjug** [comment]
Cool, thanks for your support!

**Comment by cmtonkinson** [comment]
cross post from AUR:
Looks like the nodejs package includes a `node-gyp` package which `makepkg` needs to build `atom-editor`. Unfortunately `io.js` doesn't seem to provide a `node-gyp` binary and I'm rather new to the Node ecosystem so I'm not as familiar with the toolchains.

**Comment by t-richards** [comment]
@cmtonkinson I don't believe the problem is a lack of node-gyp. My io.js install (v1.1.0) has a functional node-gyp at `/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js`. The build issues I've encountered so far are related to modules that require [`nan`](https://github.com/rvagg/nan) - maybe the version of V8 used by io.js is too new / not yet supported.

**Pull request closed without merging**
